# Generated by Django 5.0.1 on 2024-10-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name_plural': 'Cart Items'},
        ),
    ]
